services:
  fastapi-app:
    build:
      context: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8002:8002"
    networks:
      - twitter_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    command: postgres -p 5433
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - twitter_network
    ports:
      - "5433:5433"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server.crt:/server.crt:ro
      - ./server.key:/server.key:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    ports:
      - "8089:443"
    networks:
      - twitter_network
    depends_on:
      - fastapi-app

networks:
  twitter_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: